trigger:
- saucedemo_docker

pool: 
   name: test
   demands:
    - agent.name -equals saucedemo

stages:
- stage: Setup_Test_Automation
  jobs:
  - job: Setup_Test_Automation
    steps:
    - script: |
        docker compose -f docker-compose.yaml up -d
      displayName: Check and install packages and dependecies

- stage: Execute_Tests_And_Publish_Results
  jobs:
  - job: Execute_Tests_And_Publish_Results
    condition: succeededOrFailed()
    steps:
    - checkout: none
    - script: |
        docker exec test-execution pabot --pabotlib --processes 3 --verbose --argumentfile1 data/Firefox.args --argumentfile2 data/Chrome.args --argumentfile3 data/Edge.args --pythonpath . -x outputxunit.xml --outputdir TestResults tests/adding_to_cart.robot
      displayName: Execute Automated Test
      condition: succeededOrFailed()
    - task: PublishHtmlReport@1
      displayName: 'Publish HTML Report'
      inputs:
        reportDir: 'TestResults/log.html'
        condition: succeededOrFailed()
    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      inputs:
        testResultsFiles: TestResults/outputxunit.xml
        publishRunAttachments: true
        condition: succeededOrFailed()

- stage: Remove_All_Containers
  jobs:
  - job: Remove_All_Containers
    steps:
    - checkout: none
    - script: |
        docker rm test-execution -f
        docker rm chrome -f
        docker rm firefox -f
        docker rm edge -f
        docker rm selenium-hub -f
        docker ps -a
        docker images
      displayName: Remove all containers