version: "3.5"
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      VNC_NO_PASSWORD: 1
      SE_NODE_MAX_INSTANCES: 5
      SE_NODE_MAX_SESSION: 5
    ports:
      - "1907:5900"
    container_name: chrome

  edge:
    image: selenium/node-edge:latest
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      VNC_NO_PASSWORD: 1
      SE_NODE_MAX_INSTANCES: 5
      SE_NODE_MAX_SESSION: 5
    ports:
      - "1905:5900"
    container_name: edge

  firefox:
    image: selenium/node-firefox:latest
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      VNC_NO_PASSWORD: 1
      SE_NODE_MAX_INSTANCES: 5
      SE_NODE_MAX_SESSION: 5
    ports:
      - "1903:5900"
    container_name: firefox

  robot-test:
    image: test-execution
    build:
      dockerfile: Dockerfile
    volumes:
      - '../.:/tmp/.'
    depends_on:
      - selenium-hub
    entrypoint: tail -f /dev/null
    container_name: test-execution